### PR TITLE
updated DY HT bins sample

### PR DESCRIPTION
**Pull request by rcastello**
Updated list of DY HT binned sample

### CODE REVIEW

**Comment by rcastello** [comment]
@cbotta could you please merge it?

**Comment by rcastello** [comment]
thanks!

**Comment by cbotta** [comment]
actually you updated the old sample file, for all 74X analyses we used the miniAODv2. 
i.e. this one samples_13TeV_RunIISpring15MiniAODv2.py.
Can you update also this one, and check which sample file was used for the tree production?

**Comment by rcastello** [comment]
@cbotta, ok I will. R.

**Pull request merged**
